#!/usr/bin/python
# -*- coding: utf-8 -*-
# ##################################
# #__author__ = "Lululla"         ##
# #__copyright__ = "AGP Team"     ##
# #__created_by__ = "MNASR"       ##
# ##################################
from __future__ import absolute_import, print_function

CHAR_REPLACEMENTS = {
    "$": "s",
    "@": "at",
    "€": "",
    "&": " & ",
    "£": "",
    "¢": "",
    "¥": "",
    "©": "",
    "®": "",
    "™": "",
    "°": "",
    "¡": "",
    "¿": "",
    "§": "",
    "¶": "",
    "•": "",
    "–": "",  # En dash
    "—": "",  # Em dash
    "“": "",  # Left double quote
    "”": "",  # Right double quote
    "‘": "",  # Left single quote
    "’": "",  # Right single quote
    "«": "",  # Left-pointing double angle quote
    "»": "",  # Right-pointing double angle quote
    "/": "",  # Slash
    ":": " ",  # Colon
    "*": "",  # Asterisk
    "?": "",  # Question mark
    "!": "",  # Exclamation mark
    "#": "",  # Hash
    "~": "",  # Tilde
    "^": "",  # Caret
    "=": "",  # Equals
    "(": "",  # Open parenthesis
    ")": "",  # Close parenthesis
    "[": "",  # Open bracket
    "]": "",  # Close bracket
    '"': "",
    "live:": "",
    "Х/Ф": "",
    "М/Ф": "",
    "Х/ф": "",
    "18+": "",
    "18+": "",
    "16+": "",
    "16+": "",
    "12+": "",
    "12+": "",
    "7+": "",
    "7+": "",
    "6+": "",
    "6+": "",
    "0+": "",
    "0+": "",
    "+": "",
    "المسلسل العربي": "",
    "مسلسل": "",
    "برنامج": "",
    "فيلم وثائقى": "",
    "ى": "ي"
}

TITLE_SUBSTITUTIONS = [
    # Set operations (exact matches)
    ("war of the worlds", "war of the worlds:2005", "replace"),
    ("ghost in the shell", "ghost in the shell:2017", "replace"),
    ("khali balak mn geranak", "خلي بالك من جيرانك", "replace"),
    ("al qarmoti fi ard el nar", "القرموطى فى ارض النار", "replace"),
    ("batal mn warak", "بطل من ورق", "replace"),
    ("aaela zeze", "عائلة زيزي", "replace"),
    ("al rakesa wal seyasi", "الراقصة والسياسي", "replace"),
    ("al awila fil gharam", "الأولة في الغرام", "replace"),
    ("wekalt el balah", "وكالة البلح", "replace"),
    ("akher al donia", "اخر الدنيا", "replace"),
    ("haha w tofaha", "حاحا و تفاحة", "replace"),
    ("khiyana mashroua", "خيانة مشروعة", "replace"),
    ("al limbi 8 gega", "اللمبي 8 جيجا", "replace"),
    ("ghesh el zawjiya", "غش الزوجية", "replace"),
    ("samara", "سمارة", "replace"),
    ("el garag", "الجراج", "replace"),
    ("darsh", "درش", "replace"),
    ("fast & furious 7", "furious 7", "replace"),
    ("1/2", "mezzo", "replace"),
    ("c.s.i.", "csi", "replace"),
    ("c.s.i:", "csi", "replace"),
    ("c.s.i", "csi", "replace"),
    ("n.c.i.s.:", "ncis", "replace"),
    ("n.c.i.s.", "ncis", "replace"),
    ("ncis:", "ncis", "replace"),
    ("ncis - ", "ncis ", "replace"),
    ("Бандата На Рабъл", "rubble crew", "replace"),
    ("Барбароните", "Barbapapa", "replace"),
    ("ritorno al futuro:", "ritorno al futuro", "replace"),
    ("cash or trash chi offre di piu", "cash or trash", "replace"),
    ("التفاح الحرام", "yasak elma", "replace"),
    ("el moled", "المولد", "replace"),
    ("etlaouli barra", "اطلعولي بره", "replace"),
    ("wahda be wahda", "واحدة بواحدة", "replace"),
    ("el setaat mayerafoosh yekdebo", "الستات ما يعرفوش يكدبوا", "replace"),
    ("saaet rida", "ساعة رضا", "replace"),
    ("batal lel nehaya", "بطل للنهاية", "replace"),
    ("mogrem maa martabet el sharaf", "مجرم مع مرتبة الشرف", "replace"),
    ("bent el akaber", "بنت الاكابر", "replace"),
    ("sabaa al boromba", "سبع البرمبة", "replace"),
    ("al motawahesh", "yabani", "replace"),
    ("zaki shan", "زكي شان", "replace"),
    ("bani adam", "بني آدم", "replace"),
    ("mn agl zeko", "من أجل زيكو", "replace"),
    ("dam al ghazal", "دم الغزال", "replace"),
    ("el baad yazhab llmazon marten", "البعض يذهب للمأذون مرتين", "replace"),
    ("yana ya khalti", "يا أنا يا خالتي", "replace"),
    ("al markeb", "المركب", "replace"),
    ("bab al haded", "باب الحديد", "replace"),
    ("tatah", "تتح", "replace"),
    ("al harmi wal abit", "الحرامي والعبيط", "replace"),
    ("omar we salma", "عمر وسلمى", "replace"),
    ("omar we salma 2", "عمر و سلمي 2", "replace"),
    ("omar we salma 3", "عمر وسلمى 3", "replace"),
    ("el leab maa el kobaar", "اللعب مع الكبار", "replace"),
    ("ahlam omrena", "أحلام عمرنا", "replace"),
    ("lahn el khelood", "لحن الخلود", "replace"),
    ("eyoon al sakr", "عيون الصقر", "replace"),
    ("el afareet", "العفاريت", "replace"),
    ("al maadi al maghool", "الماضي المجهول", "replace"),
    ("el alb laho ahkaam", "القلب له أحكام", "replace"),
    ("al les wal kelab", "اللص والكلاب", "replace"),
    ("el kaf", "الكف", "replace"),
    ("shate el marah", "شاطئ المرح", "replace"),
    ("speed 1", "speed", "replace"),
    ("seed elnass", "سيد الناس", "replace"),
    ("ashghal sha'a", "أشغال شقة", "replace"),
    ("al shyaten al thalatha", "الشياطين الثلاثة", "replace"),
    ("aazz el habayeb", "أعز الحبايب", "replace"),
    ("al wad said al shaghal", "الواد سيد الشغال", "replace"),
    ("el zawga 13", "الزوجة 13", "replace"),
    ("khali balak mn geranak", "خلي بالك من جيرانك", "replace"),
    ("nasaf lhdha alkhata", "نأسف لهذا الخطأ", "replace"),
    ("الفناء", "the yard", "replace"),
    ("haya aw moot", "حياة أو موت", "replace"),
    ("ميرنا وخليل", "menekse and halil", "replace"),
    ("ma tigi noros", "ما تيجي نرقص", "replace"),
    ("embratoreyet meem", "إمبراطورية ميم", "replace"),
    ("el bahs aan fdeha", "البحث عن فضيحة", "replace"),
    ("hamlet ferizer", "حملة فريزر", "replace"),
    ("hamlit faraon", "حملة فرعون", "replace"),
    ("afret tranzet", "عفريت ترانزيت", "replace"),
    ("ded el hokooma", "ضد الحكومة", "replace"),
    ("a'elat al haj noaman", "عائلة الحاج نعمان", "replace"),
    ("el atawla", "العتاولة", "replace"),
    ("shaaban al fares", "شعبان الفارس", "replace"),
    ("farhan molazem adam", "فرحان ملازم آدم", "replace"),
    ("al ragol al akhtar", "الرجل الأخطر", "replace"),
    ("om rateeba", "أم رتيبة", "replace"),
    ("afwah w araneb", "أفواه وأرانب", "replace"),
    ("khaial maata", "خيال مآتة", "replace"),
    ("tharthara fawk al neel", "ثرثرة فوق النيل", "replace"),
    ("al aref", "العارف", "replace"),
    ("keda ok", "كده اوكيه", "replace"),
    ("mohtaram ela 1/4", "محترم إلا ربع", "replace"),
    ("ala sada al khalkhal", "jhanak", "replace"),
    ("masrah masr", "مسرح مصر", "replace"),
    ("aserati", "meri zindagi hai tu", "replace"),
    ("al motawahesh", "wild heart", "replace"),
    ("the protg", "the protege", "replace"),
    ("aroosa w gooz ersaan", "عروسة و جوز عرسان", "replace"),
    ("al alami", "العالمي", "replace"),
    ("ewa weshak", "اوعى وشك", "replace"),
    ("samir w shahir w bahir", "سمير و شهير و بهير", "replace"),
    ("taaer al layl el hazien", "طائر الليل الحزين", "replace"),
    ("el badla", "البدلة", "replace"),
    ("haret borgwan", "حارة برجوان", "replace"),
    ("al waad", "الوعد", "replace"),
    ("karakoon fel share", "كراكون في الشارع", "replace"),
    ("habibi naeman", "حبيبي نائما", "replace"),
    ("ismail yassin fi mostashfa el maganeen", "إسماعيل ياسين في مستشفي المجانين", "replace"),
    ("laf we dawran", "لف ودوران", "replace"),
    ("boltia al ayma", "بلطية العايمة", "replace"),
    ("code 36", "كود 36", "replace"),
    ("ice cream fi gilem", "آيس كريم في جليم", "replace"),
    ("tata we reka we kathem bk", "طأطأ وريكا وكاظم بيه", "replace"),
    ("al hob al awal", "الحب الأول", "replace"),
    ("fast & furious", "fast furious:2009", "replace"),
    ("الكبير", "الكبير اوى", "replace"),
    ("awdat akhtar ragol fi al alam", "عودة اخطر رجل في العالم", "replace"),
    ("tabakh al rayis", "طباخ الريس", "replace"),
    ("welad el aam", "ولاد العم", "replace"),
    ("bank el haz", "بنك الحظ", "replace"),
    ("kelmet sharaf", "كلمة شرف", "replace"),
    ("seraa fel neel", "conflict in the nile", "replace"),
    ("al mash mohandis hassan", "المش مهندس حسن", "replace"),
    ("burlesk", "burlesque", "replace"),
    ("kockat", "kokak:2011", "replace"),
    ("habibati.. man takoun?", "ghum hai kisikey pyaar meiin", "replace"),
    ("Malkolmi Mes Te Tjereve", "malcolm in the middle", "replace"),
    ("سدف", "مسلسل سدف", "replace"),
    ("فاطمة", "what is fatmagul's fault?", "replace"),
    ("um 44", "أم 44", "replace"),
    ("saw 2", "saw ii", "replace"),
    ("saw 3", "saw iii", "replace"),
    ("saw 4", "saw iv", "replace"),
    ("saw 5", "saw v", "replace"),
    ("saw 6", "saw vi", "replace"),
    ("tatah", "تتح", "replace"),
    ("القبضاى", "karadayi", "set"),
    ("garema ella", "جريمة إلا ربع", "set"),
    ("فاصل من اللحظات", "فاصل من اللحظات اللذيذة", "set"),
    ("habibati man takoun", "ghum hai kisikey pyaar meiin", "set"),
    ("forget the lyrics", "dont forget the lyrics", "set"),
    ("dr house", "house md", "set"),
    ("superman & lois", "superman e lois", "set"),
    ("lois & clark", "superman e lois", "set"),
    ("una 44 magnum per", "magnumxx", "set"),
    ("john q", "johnq", "set"),
    ("il ritorno di colombo", "colombo", "set"),
    ("lingo: parole", "lingo", "set"),
    ("heartland", "heartland", "set"),
    ("io & marilyn", "io e marilyn", "set"),
    ("giochi olimpici parigi", "olimpiadi di parigi", "set"),
    ("bruno barbieri", "brunobarbierix", "set"),
    ("anni '60", "anni 60", "set"),
    ("cortesie per gli ospiti", "cortesieospiti", "set"),
    ("tg regione", "tg3", "set"),
    ("tg1", "tguno", "set"),
    ("planet earth", "planet earth", "set"),
    ("studio aperto", "studio aperto", "set"),
    ("josephine ange gardien", "josephine ange gardien", "set"),
    ("josephine angelo", "josephine ange gardien", "set"),
    ("elementary", "elementary", "set"),
    ("squadra speciale cobra 11", "squadra speciale cobra 11", "set"),
    ("criminal minds", "criminal minds", "set"),
    ("i delitti del barlume", "i delitti del barlume", "set"),
    ("senza traccia", "senza traccia", "set"),
    ("hudson e rex", "hudson e rex", "set"),
    ("ben-hur", "ben-hur", "set"),
    ("alessandro borghese - 4 ristoranti", "alessandroborgheseristoranti", "set"),
    ("alessandro borghese: 4 ristoranti", "alessandroborgheseristoranti", "set"),
    ("amici di maria", "amicimaria", "set"),
    ("csi miami", "csi miami", "set"),
    ("indiana jones ii", "Indiana Jones and the Temple of Doom", "set"),
    ("csi: miami", "csi miami", "set"),
    ("csi: scena del crimine", "csi scena del crimine", "set"),
    ("csi: new york", "csi new york", "set"),
    ("csi: vegas", "csi vegas", "set"),
    ("csi: cyber", "csi cyber", "set"),
    ("csi: immortality", "csi immortality", "set"),
    ("csi: crime scene talks", "csi crime scene talks", "set"),
    ("ncis unità anticrimine", "ncis unità anticrimine", "set"),
    ("ncis unita anticrimine", "ncis unita anticrimine", "set"),
    ("ncis new orleans", "ncis new orleans", "set"),
    ("ncis los angeles", "ncis los angeles", "set"),
    ("ncis origins", "ncis origins", "set"),
    ("ncis hawai", "ncis hawai", "set"),
    ("ncis sydney", "ncis sydney", "set"),
    ("ncis tony & ziva", "ncis tony & ziva", "set"),
    ("ritorno al futuro - parte iii", "ritornoalfuturoparteiii", "set"),
    ("ritorno al futuro - parte ii", "ritornoalfuturoparteii", "set"),
    ("walker, texas ranger", "walker texas ranger", "set"),
    ("e.r.", "ermediciinprimalinea", "set"),
    ("alexa: vita da detective", "alexa vita da detective", "set"),
    ("delitti in paradiso", "delitti in paradiso", "set"),
    ("modern family", "modern family", "set"),
    ("shaun: vita da pecora", "shaun", "set"),
    ("calimero", "calimero", "set"),
    ("i puffi", "i puffi", "set"),
    ("stuart little", "stuart little", "set"),
    ("gf daily", "grande fratello", "set"),
    ("grande fratello", "grande fratello", "set"),
    ("castle", "castle", "set"),
    ("seal team", "seal team", "set"),
    ("fast forward", "fast forward", "set"),
    ("un posto al sole", "un posto al sole", "set"),
    ("cash or trash chi offre di piu", "cash or trash", "set"),
]

PREDEFINED_SKIP_WORDS = [
    "live",
    "uzivo ",
    "bugarski kup",
    "moto gp",
    "zlatni momenti yu sporta",
    "rukomet",
    "emisija",
    "one zive za sport",
    "atp",
    "soccer",
    "tennis",
    "wta",
    "fifa",
    "uefa",
    "Уефа",
    "champions league",
    "premier league",
    "bundesliga",
    "laliga",
    "liga",
    "serie a",
    "nba",
    "nfl",
    "mlb",
    "motogp",
    "formula 1",
    "no information",
    "kampionati portugez",
    "futbale",
    "motokros",
    "kampionati gjerman",
    "highlighty",
    "sport news",
    "nogomet",
    "hokej",
    "aba liga",
    "mnr",
    "najava programa",
    "programet",
    "euroleague",
    "euronews",
    "news",
    "boks",
    "info",
    "scoop with raya",
    "action zone",
    "dmc",
    "cbc",
    "concert",
    "passion to the extreme",
    "sexy",
    "barely legal",
    "hardcore",
    "extasy",
    "lesbian",
    "erotic",
    "famous and up",
    "snooker",
    "hardcore",
    "عرب وود",
    "اغاني من حفلات قديمة",
    "روايع",
    "روتانا",
    "celebrity scoop",
    "making the movies",
    "action zone",
    " 18 ",
    "program per te rritur",
    "adult movie",
    "yефа Лига Европа",
    "boxing",
    "grand slam",
    "mma",
    "piłka",
    "ma' waleed",
    "baseball",
    "shortlist",
    "prljava vožnja",
    "najava",
    "europa liga",
    "m. t-a",
    "films & stars"
]

FINAL_KNOWN_ALIASES = {
    "xxxxxx": "60",
    "magnumxx": "una 44 magnum per l ispettore",
    "amicimaria": "amici di maria",
    "alessandroborgheseristoranti": "alessandro borghese - 4 ristoranti",
    "brunobarbierix": "bruno barbieri - 4 hotel",
    "johnq": "john q",
    "il ritorno di colombo": "colombo",
    "cortesieospiti": "cortesie per gli ospiti",
    "ermediciinprimalinea": "er medici in prima linea",
    "ritornoalfuturoparteiii": "ritorno al futuro parte iii",
    "ritornoalfuturoparteii": "ritorno al futuro parte ii",
    "tguno": "tg1",
}
